package com.example.redditapp.models.child

import com.google.gson.annotations.SerializedName

data class ChildData(
    @SerializedName("approved_at_utc") val approved_at_utc :Any? = null,
    @SerializedName("subreddit") val subreddit :Any? = null,
    @SerializedName("selftext") val selftext :Any? = null,
    @SerializedName("author_fullname") val author_fullname :Any? = null,
    @SerializedName("saved") val saved :Any? = null,
    @SerializedName("mod_reason_title") val mod_reason_title :Any? = null,
    @SerializedName("gilded") val gilded : Any? = null,
    @SerializedName("clicked") val clicked :Any? = null,
    @SerializedName("title") val title :String,
    @SerializedName("link_flair_richtext") val link_flair_richtext :Any? = null,
    @SerializedName("subreddit_name_prefixed") val subreddit_name_prefixed :Any? = null,
    @SerializedName("hidden") val hidden :Any? = null,
    @SerializedName("pwls") val pwls : Any? = null,
    @SerializedName("link_flair_css_class") val link_flair_css_class :Any? = null,
    @SerializedName("downs") val downs : Any? = null,
    @SerializedName("thumbnail_height") val thumbnail_height : Any? = null,
    @SerializedName("top_awarded_type") val top_awarded_type :Any? = null,
    @SerializedName("hide_score") val hide_score :Any? = null,
    @SerializedName("name") val name : Any? = null,
    @SerializedName("quarantine") val quarantine :Any? = null,
    @SerializedName("link_flair_text_color") val link_flair_text_color :Any? = null,
    @SerializedName("upvote_ratio") val upvote_ratio : Any? = null,
    @SerializedName("author_flair_background_color") val author_flair_background_color :Any? = null,
    @SerializedName("subreddit_type") val subreddit_type :Any? = null,
    @SerializedName("ups") val ups : Any? = null,
    @SerializedName("total_awards_received") val total_awards_received : Any? = null,
    @SerializedName("media_embed") val adv : Any? = null,
    @SerializedName("thumbnail_width") val thumbnail_width : Any? = null,
    @SerializedName("author_flair_template_id") val author_flair_template_id :Any? = null,
    @SerializedName("is_original_content") val is_original_content :Any? = null,
    @SerializedName("user_reports") val user_reports :Any? = null,
    @SerializedName("secure_media") val secure_media :Any? = null,
    @SerializedName("is_reddit_media_domain") val is_reddit_media_domain :Any? = null,
    @SerializedName("is_meta") val is_meta :Any? = null,
    @SerializedName("category") val category :Any? = null,
    @SerializedName("secure_Any? = null") val secure_Any: Any? = null,
    @SerializedName("link_flair_text") val link_flair_text :Any? = null,
    @SerializedName("can_mod_post") val can_mod_post :Any? = null,
    @SerializedName("score") val score : Any? = null,
    @SerializedName("approved_by") val approved_by :Any? = null,
    @SerializedName("author_premium") val author_premium :Any? = null,
    @SerializedName("thumbnail") val thumbnail :String,
    @SerializedName("edited") val edited :Any? = null,
    @SerializedName("author_flair_css_class") val author_flair_css_class :Any? = null,
    @SerializedName("author_flair_richtext") val author_flair_richtext :Any? = null,
    @SerializedName("gildings") val gildings : Any? = null,
    @SerializedName("post_h") val post: Any? = null,
    @SerializedName("content_categories") val content_categories :Any? = null,
    @SerializedName("is_self") val is_self :Any? = null,
    @SerializedName("mod_note") val mod_note :Any? = null,
    @SerializedName("created") val created : Any? = null,
    @SerializedName("link_flair_type") val link_flair_type :Any? = null,
    @SerializedName("wls") val wls : Any? = null,
    @SerializedName("removed_by_category") val removed_by_category :Any? = null,
    @SerializedName("banned_by") val banned_by :Any? = null,
    @SerializedName("author_flair_type") val author_flair_type :Any? = null,
    @SerializedName("domain") val domain :Any? = null,
    @SerializedName("allow_live_comments") val allow_live_comments :Any? = null,
    @SerializedName("selftext_html") val selftext_html :Any? = null,
    @SerializedName("likes") val likes :Any? = null,
    @SerializedName("suggested_sort") val suggested_sort :Any? = null,
    @SerializedName("banned_at_utc") val banned_at_utc :Any? = null,
    @SerializedName("url_overridden_by_dest") val url_overridden_by_dest :Any? = null,
    @SerializedName("view_count") val view_count :Any? = null,
    @SerializedName("archived") val archived :Any? = null,
    @SerializedName("no_follow") val no_follow :Any? = null,
    @SerializedName("is_crosspostable") val is_crosspostable :Any? = null,
    @SerializedName("pinned") val pinned :Any? = null,
    @SerializedName("over_18") val over_18 :Any? = null,
    @SerializedName("preview") val preview : Any? = null,
    @SerializedName("all_awardings") val all_awardings :Any? = null,
    @SerializedName("awarders") val awarders :Any? = null,
    @SerializedName("media_only") val media_only :Any? = null,
    @SerializedName("can_gild") val can_gild :Any? = null,
    @SerializedName("spoiler") val spoiler :Any? = null,
    @SerializedName("locked") val locked :Any? = null,
    @SerializedName("author_flair_text") val author_flair_text :Any? = null,
    @SerializedName("treatment_tags") val treatment_tags :Any? = null,
    @SerializedName("visited") val visited :Any? = null,
    @SerializedName("removed_by") val removed_by :Any? = null,
    @SerializedName("num_reports") val num_reports :Any? = null,
    @SerializedName("distinguished") val distinguished :Any? = null,
    @SerializedName("subreddit_id") val subreddit_id :Any? = null,
    @SerializedName("mod_reason_by") val mod_reason_by :Any? = null,
    @SerializedName("removal_reason") val removal_reason :Any? = null,
    @SerializedName("link_flair_background_color") val link_flair_background_color :Any? = null,
    @SerializedName("id") val id :Any? = null,
    @SerializedName("is_robot_indexable") val is_robot_indexable :Any? = null,
    @SerializedName("report_reasons") val report_reasons :Any? = null,
    @SerializedName("author") val author :String,
    @SerializedName("discussion_type") val discussion_type :Any? = null,
    @SerializedName("num_comments") val num_comments : String,
    @SerializedName("send_replies") val send_replies :Any? = null,
    @SerializedName("whitelist_status") val whitelist_status :Any? = null,
    @SerializedName("contest_mode") val contest_mode :Any? = null,
    @SerializedName("mod_reports") val mod_reports :Any? = null,
    @SerializedName("author_patreon_flair") val author_patreon_flair :Any? = null,
    @SerializedName("author_flair_text_color") val author_flair_text_color :Any? = null,
    @SerializedName("permalink") val permalink :Any? = null,
    @SerializedName("parent_whitelist_status") val parent_whitelist_status :Any? = null,
    @SerializedName("stickied") val stickied :Any? = null,
    @SerializedName("url") val url :Any? = null,
    @SerializedName("subreddit_subscribers") val subreddit_subscribers : Any? = null,
    @SerializedName("created_utc") val created_utc : Long,
    @SerializedName("num_crossposts") val num_crossposts : Any? = null,
    @SerializedName("media") val media :Any? = null,
    @SerializedName("is_video") val is_video :Any? = null
)
